import'./jquery'

import 'admin-lte/plugins/fontawesome-free/css/all.min.css'
import 'admin-lte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css'
import 'admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css'
import 'admin-lte/plugins/jqvmap/jqvmap.min.css'
import 'admin-lte/dist/css/adminlte.min.css'
import 'admin-lte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css'
import 'admin-lte/plugins/daterangepicker/daterangepicker.css'
import 'admin-lte/plugins/summernote/summernote-bs4.min.css'

import 'admin-lte/plugins/jquery/jquery'
import 'admin-lte/plugins/jquery-ui/jquery-ui'
import 'admin-lte/plugins/bootstrap/js/bootstrap.bundle'
import 'admin-lte/plugins/chart.js/Chart'
import 'admin-lte/plugins/sparklines/sparkline.js'
import 'admin-lte/plugins/jqvmap/jquery.vmap'
import 'admin-lte/plugins/jqvmap/maps/jquery.vmap.usa.js'
import 'admin-lte/plugins/jquery-knob/jquery.knob.min.js'
import 'admin-lte/plugins/moment/moment.min.js'
import 'admin-lte/plugins/daterangepicker/daterangepicker.js'
import 'admin-lte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4'
import 'admin-lte/plugins/summernote/summernote-bs4'
import 'admin-lte/plugins/overlayScrollbars/js/OverlayScrollbars'
import 'admin-lte/dist/js/adminlte.js'
import 'admin-lte/dist/js/pages/dashboard.js'